name: Create Branch and Push Changes

on:
  repository_dispatch:
    types: [custom_event]

jobs:
  create-branch-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Create Branch
        run: |
          BRANCH_NAME="new-branch"
          git checkout -b $BRANCH_NAME
          echo "${{ github.event.client_payload.custom_data }}" > a.txt
          git add .
          git commit -m "Add file with custom data"
          git push origin $BRANCH_NAME


      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'new changes received',
              owner,
              repo,
              head: '${{ env.BRANCH_NAME }}',
              base: 'main',
            });
