name: Auto Merge PR on Approval and release a Tag

on:
  pull_request_review:
    types:
      - submitted

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set branch name
      run: |
        BRANCH_NAME=$(jq --raw-output .pull_request.base.ref "$GITHUB_EVENT_PATH")
        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

    - name: Auto-merge if approved
      run: |
        # Get the pull request number
        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

        # Check if the pull request is approved
        APPROVALS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                     "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/reviews" | \
                     jq '.[] | select(.state=="APPROVED")')

        if [ -n "$APPROVALS" ]; then
          # Merge the pull request
          curl -X PUT -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/merge"
        fi

    - name: Create an incremental release
      uses: aurestic/incrementarl-create-release@master
      with:
        message: Upgrade version
        prev_tag: 'v'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete the branch
      run: |
        git push origin --delete ${{ env.BRANCH_NAME }}
